Document: hciattach-rpi3
Title: Debian hciattach-rpi3 Manual
Author: <insert document author here>
Abstract: This manual describes what hciattach-rpi3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hciattach-rpi3/hciattach-rpi3.sgml.gz

Format: postscript
Files: /usr/share/doc/hciattach-rpi3/hciattach-rpi3.ps.gz

Format: text
Files: /usr/share/doc/hciattach-rpi3/hciattach-rpi3.text.gz

Format: HTML
Index: /usr/share/doc/hciattach-rpi3/html/index.html
Files: /usr/share/doc/hciattach-rpi3/html/*.html
